parameters:
  - name: settings
    type: object
  - name: resources
    type: object

jobs:
  
  - ${{ each resource in parameters.resources }}:  

    - ${{ if eq(resource.enabled, 'true') }}:

      - ${{ if eq(resource.type, 'appConfiguration') }}:
        - template: /src/definitions/cloud/azure/appConfiguration/jobs/appConfiguration-build-jobs.yml
          parameters:
            settings: ${{ parameters.settings }}
            resource: ${{ resource }}

      - ${{ if eq(resource.type, 'resourceGroup') }}:
        - template: /src/definitions/cloud/azure/resourceGroup/jobs/resourceGroup-build-jobs.yml
          parameters:
            settings: ${{ parameters.settings }}
            resource: ${{ resource }}

      - ${{ if eq(resource.type, 'networkHub') }}:
        - ${{ if eq(resource.deploy.infrastructure.type, 'terraform') }}:
          - template: /src/definitions/cloud/azure/iac/terraform/terraform-build-jobs.yml
            parameters:
              settings: ${{ parameters.settings }}
              resource: ${{ resource }}
              iacSettings: 
                templatesDirectory: src/definitions/cloud/azure/landingZones/platform/connectivity/hubNetwork

        # - ${{ if eq(resource.deploy.infrastructure.type, 'bicep') }}:
        # - ${{ if eq(resource.deploy.infrastructure.type, 'powershell') }}:
        
      
