
parameters:
  - name: settings
    type: object
  - name: resources
    type: object
  - name: environment
    type: string

jobs:

  - ${{ each resource in parameters.resources }}:
    - ${{ if eq(resource.enabled, 'true') }}:          
      
      - ${{ if eq(resource.type, 'appConfiguration') }}:
        - template: /src/definitions/cloud/azure/appConfiguration/jobs/appConfiguration-deploy-jobs.yml
          parameters:
            settings: ${{ parameters.settings }}                  
            environment: ${{ parameters.environment }}
            resource: ${{ resource }}

      - ${{ if eq(resource.type, 'resourceGroup') }}:
        - template: /src/definitions/cloud/azure/resourceGroup/jobs/resourceGroup-deploy-jobs.yml
          parameters:
            settings: ${{ parameters.settings }}                  
            environment: ${{ parameters.environment }}
            resource: ${{ resource }}
      
      # - ${{ if eq(resource.type, 'terraform') }}:
      #   - template: /src/definitions/cloud/azure/resourceGroup/jobs/resourceGroup-deploy-jobs.yml
      #     parameters:
      #       settings: ${{ parameters.settings }}                  
      #       environment: ${{ parameters.environment }}
      #       resource: ${{ resource }}                 