parameters:
  - name: workloadSettings
    type: object

jobs:

  - job: ${{ variables.workloadName }}_build
    displayName: Building IaC Artifacts
    # variables:
      
    steps:
      - checkout: self

      # TODO: Move to specific file?
      # - task: CopyFiles@2
      #   displayName: Copying Utilities files
      #   inputs:
      #     SourceFolder: /utilities
      #     Contents: |
      #       **\*
      #     TargetFolder: $(build.artifactstagingdirectory)/utilities

      - task: CopyFiles@2
        displayName: Copying Workload files
        inputs:
          SourceFolder: /workloads/platform/identity-access-management/$(workloadName)@ReleaseEngine # tenant-provisioning
          Contents: |
            **\*.ps1
            **\*.ps1
          TargetFolder: $(outputDirectory)

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(build.artifactstagingdirectory)
          artifact: powershell
          publishLocation: pipeline      

      # - task: PublishBuildArtifacts@1
      #   inputs:
      #     pathToPublish: $(Build.ArtifactStagingDirectory)
      #     artifactName: $(configFilesArtifactName)