parameters:
  - name: settings
    type: object
  - name: resource
    type: object

jobs:
  - job: appConfigurationBuildJob
    displayName: App Configuration Build Job
    steps:

      - template: /src/definitions/cloud/azure/_bicep/tasks/bicep-build-tasks.yml
        parameters:
          resourceType: ${{ parameters.resource.type }}

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactstagingdirectory)'
          artifact: keyVault
          publishLocation: 'pipeline'