parameters:
- name: settings
  type: object
- name: resource
  type: object  
- name: environment
  type: string


jobs:
  - deployment: 
    displayName: Azure App Configuration Deployment
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Creating Resource Group '${{ parameters.resource.name }}' by IaC
              inputs:
                azureResourceManagerConnection: '${{ parameters.settings.azure.subscription.serviceConnection }}'
                subscriptionId: ${{ parameters.settings.azure.subscription.subscriptionId }}
                action: 'Create Or Update Resource Group'
                resourceGroupName: ${{ parameters.settings.azure.resourceGroup.name }}
                location: ${{ parameters.settings.azure.resourceGroup.location }}
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)/${{ parameters.resource.type }}/infrastructure/${{ parameters.resource.type }}.json'
                overrideParameters: >
                  -resourceGroupName ${{ parameters.resource.name }}
                  -resourceGroupLocation ${{ parameters.settings.azure.resourceGroup.location }}
                deploymentMode: 'Incremental'
                deploymentOutputs: 'ArmOutputs'
