parameters:
  - name: settings
    type: object
  - name: resource
    type: object
  - name: iacSettings
    type: object    

jobs:
  - job: ${{ parameters.resource.jobName }}_Build
    displayName: Terraform Build Job
    steps:

      - template: /src/definitions/cloud/azure/iac/terraform/jobs/tasks/terraform-build-tasks.yml      
        parameters:
          resourceType: ${{ parameters.resource.type }}
          iacSettings: ${{ parameters.iacSettings }}

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactstagingdirectory)'
          artifact: terraform
          publishLocation: 'pipeline'