parameters:
  - name: resourceType
    type: object
  - name: outDir
    type: string
    default: infrastructure
  - name: iacSettings
    type: object

steps:
  - checkout: ReleaseEngine

  - powershell: |
      Get-ChildItem $(Build.SourcesDirectory) -Recurse

  - powershell: |
      Write-Host "##[command]Running Terraform Init"
      terraform init -backend=false -input=false
    workingDirectory: ${{ parameters.iacSettings.templatesDirectory }}
    displayName: Terraform init

  - powershell: |
      Write-Host "##[command]Running Terraform Validate"
      terraform validate
    workingDirectory: ${{ parameters.iacSettings.templatesDirectory }}

    displayName: Terraform validate  

  - powershell: |
      Write-Host "##[command]Check Terraform Format"
      terraform fmt -diff -check -recursive -write=false
    workingDirectory: ${{ parameters.iacSettings.templatesDirectory }}
    displayName: Terraform format

  - powershell: |
      Copy-Item "*.tf" -Destination "$(build.artifactstagingdirectory)"
    workingDirectory: ${{ parameters.iacSettings.templatesDirectory }}
    displayName: Copying terraform files
    env:
      outDir: ${{ parameters.outDir }}

  # - powershell: |

  #     if(Test-Path "$(Build.SourcesDirectory)/$(releaseEngineRepositoryName)"){
  #       $sourceDirectory = "$(Build.SourcesDirectory)/$(releaseEngineRepositoryName)"
  #     }else{
  #       $sourceDirectory = "$(Build.SourcesDirectory)"
  #     }

  #     $file = Join-Path $sourceDirectory $env:bicepFilePath

  #     Write-Host "##[section]Building bicep file: $file"

  #     Write-Host $file

  #     New-Item -ItemType Directory -Force -Path $(build.artifactstagingdirectory)/$env:outDir
  #     az bicep build --file $file --outdir $(build.artifactstagingdirectory)/$env:outDir

  #     Get-ChildItem $(build.artifactstagingdirectory)/$env:outDir
  #   displayName: 'Build bicep artifact' 
  #   env:
  #     bicepFilePath: /src/definitions/cloud/azure/${{ parameters.resourceType }}/bicep/${{ parameters.resourceType }}-iac.bicep
  #     outDir: ${{ parameters.outDir }}

      