parameters:
  - name: resource
    type: object
  - name: outDir
    type: string
    default: infrastructure
  - name: iacSettings
    type: object

steps:
  - checkout: ReleaseEngine

  - powershell: |
      Get-ChildItem $(Build.SourcesDirectory) -Recurse

  - powershell: |
      Write-Host "##[command]Running Terraform Init"
      terraform init -backend=false -input=false
    workingDirectory: ${{ parameters.iacSettings.templatesDirectory }}
    displayName: Terraform init

  - powershell: |
      Write-Host "##[command]Running Terraform Validate"
      terraform validate
    workingDirectory: ${{ parameters.iacSettings.templatesDirectory }}

    displayName: Terraform validate  

  - powershell: |
      Write-Host "##[command]Check Terraform Format"
      terraform fmt -diff -check -recursive -write=false
    workingDirectory: ${{ parameters.iacSettings.templatesDirectory }}
    displayName: Terraform format

  - powershell: |
      Copy-Item "*.tf" -Destination "$(build.artifactstagingdirectory)"
    workingDirectory: ${{ parameters.iacSettings.templatesDirectory }}
    displayName: Copying terraform definitions

  - powershell: |
      Copy-Item "*.tfvars" -Destination "$(build.artifactstagingdirectory)/variables/"
    workingDirectory: ${{ parameters.resource.deploy.infrastructure.variables }}
    displayName: Copying terraform variables  
