parameters:
  - name: settings
    type: object
  - name: resource
    type: object

jobs:
  - job: ${{ parameters.resource.jobName }}_Build
    displayName: Resource Group Build Job
    steps:

      - template: /src/definitions/cloud/azure/iac/terraform/terraform-build-tasks.yml
        parameters:
          resourceType: ${{ parameters.resource.type }}

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactstagingdirectory)'
          artifact: resourceGroup
          publishLocation: 'pipeline'