parameters:
  - name: workloadSettings
    type: object

variables:
  - name: serviceConnection
    value: ServiceConnection
  - template: /templates/workloads/platform/identity-access-management/tenant-provisioning/tests/_config/metadata.yml

stages:

  - template: /pipelines/02-stages/iac.build.stage.yml
    parameters:
      workloadSettings: ${{ parameters.workloadSettings }}

  # - template: /pipelines/02-stages/iac.deploy.stage.yml
  #   parameters:
  #     settings: ${{ parameters.settings }}
  
