parameters:
  - name: workloadSettings
    type: object

jobs:

  - job: ${{ variables.workload }}_build
    displayName: Building IaC Artifacts
      
    steps:
      - checkout: self

      - task: CopyFiles@2
        displayName: Copying Workload content
        inputs:
          SourceFolder: templates/workloads/$(landingZoneType)/$(designArea)/$(workload)
          Contents: |
            **
          TargetFolder: $(build.artifactstagingdirectory)/${{ variables.workload }}
          flattenFolders: false

      - task: CopyFiles@2
        displayName: Copying Utilities content
        inputs:
          SourceFolder: templates/utilities
          Contents: |
            **
          TargetFolder: $(build.artifactstagingdirectory)/utilities
          flattenFolders: false

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(build.artifactstagingdirectory)/${{ variables.workload }}
          artifact: ${{ variables.workload }}
          publishLocation: pipeline

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(build.artifactstagingdirectory)/utilities
          artifact: ${{ variables.workload }}
          publishLocation: pipeline