parameters:
  - name: workloadSettings
    type: object

jobs:

  - job: ${{ variables.workload }}_build
    displayName: Building IaC Artifacts
    # variables:
      
    steps:
      - checkout: self

      - task: CopyFiles@2
        displayName: Copying Utilities content
        inputs:
          SourceFolder: templates/utilities
          Contents: |
            **
          TargetFolder: $(build.artifactstagingdirectory)
          flattenFolders: false

      - task: CopyFiles@2
        displayName: Copying Workload content
        inputs:
          SourceFolder: templates/workloads/$(landingZoneType)/$(designArea)/$(workload)
          Contents: |
            **
          TargetFolder: $(build.artifactstagingdirectory)
          flattenFolders: false

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(build.artifactstagingdirectory)
          artifact: artifact
          publishLocation: pipeline      