parameters:
  - name: workloadSettings
    type: object
  - name: jobSettings
    type: object

jobs:
  - deployment: workload_deployment #TODO: parametrize
    displayName: Azure Deployment
    environment: ${{ parameters.jobSettings.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - powershell: |
                Get-ChildItem $(Pipeline.Workspace) -Recurse
                
            
            # - task: AzureResourceManagerTemplateDeployment@3
            #   displayName: Creating Resource Group '${{ parameters.resource.name }}' by IaC
            #   inputs:
            #     deploymentScope: 'Subscription'
            #     azureResourceManagerConnection: '${{ parameters.settings.azure.subscription.serviceConnection }}'
            #     subscriptionId: ${{ parameters.settings.azure.subscription.subscriptionId }}
            #     action: 'Create Or Update Resource Group'
            #     resourceGroupName: ${{ parameters.settings.azure.resourceGroup.name }}
            #     location: ${{ parameters.settings.azure.resourceGroup.location }}
            #     templateLocation: 'Linked artifact'
            #     csmFile: '$(Pipeline.Workspace)/${{ parameters.resource.type }}/infrastructure/${{ parameters.resource.type }}-iac.json'
            #     overrideParameters: >
            #       -resourceGroupName ${{ parameters.resource.name }}
            #       -resourceGroupLocation ${{ parameters.settings.azure.resourceGroup.location }}
            #     deploymentMode: 'Incremental'
            #     deploymentOutputs: 'ArmOutputs'
