parameters:
  - name: workloadSettings
    type: object

jobs:

  - job: ${{ variables.workload }}_build
    displayName: Building IaC Artifacts
    # variables:
      
    steps:
      - checkout: self

      - task: CopyFiles@2
        displayName: Copying Utilities files
        inputs:
          SourceFolder: templates/utilities
          Contents: |
            **\*
          TargetFolder: $(build.artifactstagingdirectory)

      - task: CopyFiles@2
        displayName: Copying Workload files
        inputs:
          SourceFolder: templates/workloads/$(landingZoneType)/$(designArea)/$(workload) # tenant-provisioning
          Contents: |
            **\*.ps1
          TargetFolder: $(build.artifactstagingdirectory)

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(build.artifactstagingdirectory)
          artifact: powershell
          publishLocation: pipeline      

      # - task: PublishBuildArtifacts@1
      #   inputs:
      #     pathToPublish: $(Build.ArtifactStagingDirectory)
      #     artifactName: $(configFilesArtifactName)