parameters:
  - name: workloadSettings
    type: object

jobs:

  - job: ${{ variables.workload }}_build
    displayName: Building IaC Artifacts
      
    steps:
      - task: CopyFiles@2
        displayName: Copying Workload content
        inputs:
          SourceFolder: templates/workloads/$(landingZoneType)/$(designArea)/$(workload)
          Contents: |
            **
            !tests/**
          TargetFolder: $(build.artifactstagingdirectory)/$(workload)
          flattenFolders: false

      - task: CopyFiles@2
        displayName: Copying Utilities content
        inputs:
          SourceFolder: templates/utilities
          Contents: |
            **
          TargetFolder: $(build.artifactstagingdirectory)/utilities
          flattenFolders: false

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(build.artifactstagingdirectory)/$(workload)
          artifactName: pipeline

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(build.artifactstagingdirectory)/utilities
          artifactName: utilities